### ISSUE TITLE
messy js file

### ISSUE THREAD

**Issue by LeahJKH** [AndreK-B06/cookie-clicker-Karl-clicer-#1]
you should consider adding more complex variable names too clean up the code for easier readablity and maybe clean it up with comments and such. hope this helped :)

**Comment by Andre-V-K** [comment]
Thanks for the feedback. This project is temporarily put on hold, but what you were writing about were some of the things I wanted to address when I start working on it again. Please continue to use my product and comment if you see problems in the future when I start working on it again :)
